env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAIYAXFUAHXOWP2MJA

jobs:
  include:
    - stage: Tests
      name: Linting
      os: linux
      sudo: required
      language: node_js
      node_js: 8
      cache: npm
      install:
        - npm install --silent
      script:
        - npm run lint

    - stage: Tests
      name: Unit tests - Node.js 6
      os: linux
      sudo: required
      language: node_js
      node_js:
        - 6
      cache: npm
      install:
        - npm install --silent
      script:
        - npm run unit-testing

    - stage: Tests
      name: Unit tests - Node.js 8
      os: linux
      sudo: required
      language: node_js
      node_js:
        - 8
      cache: npm
      install:
        - npm install --silent
      script:
        - npm run unit-testing
      after_script:
        - npm run codecov

    - stage: Tests
      name: Unit tests - Node.js 10
      os: linux
      sudo: required
      language: node_js
      node_js:
        - 10
      cache: npm
      install:
        - npm install --silent
      script:
        - npm run unit-testing
      after_script:
        - npm run codecov

    - stage: Tests
      name: Dead link check
      language: node_js
      node_js: 10
      if: type = pull_request OR type = push AND branch =~ /^master|[0-9]+-(dev|stable)$/ OR type = cron

      before_script:
        - npm ci
        - npm run doc-prepare
        - $(npm bin)/kuzdoc iterate-repos:install --repos_path doc/framework/.repos/
        - $(npm bin)/kuzdoc framework:link -d /official-plugins/cloudinary/1/ -v 1
      script:
        - gem install typhoeus
        - cd doc/framework/ && HYDRA_MAX_CONCURRENCY=20 ruby .ci/dead-links.rb -p src/official-plugins/cloudinary/1/

    - stage: Deployment Doc Dev
      name: Deploy next-docs.kuzzle.io
      if: type = push AND branch =~ .*-dev
      language: node_js
      node_js: 10
      env:
        - BRANCH=dev
        - NODE_ENV=production
        - S3_BUCKET=docs-next.kuzzle.io
        - CLOUDFRONT_DISTRIBUTION_ID=E2ZCCEK9GRB49U
        - AWS_DEFAULT_REGION=us-west-2

      addons:
        apt:
          packages:
            - python
            - python-pip

      install:
        - pip install awscli --upgrade --user
        - npm ci

      script:
        - npm run doc-prepare
        - npm run doc-build

      deploy:
        provider: script
        script:
          - npm run doc-upload
        skip_cleanup: true
        on:
          all_branches: true

      after_deploy:
        - npm run doc-cloudfront

    - stage: Deployment Doc Prod
      name: Deploy docs.kuzzle.io
      if: type = push AND branch =~ /^master|[0-9]+-stable$/
      language: node_js
      node_js: 10
      env:
        - NODE_ENV=production
        - S3_BUCKET=docs.kuzzle.io
        - CLOUDFRONT_DISTRIBUTION_ID=E3D6RP0POLCJMM
        - AWS_DEFAULT_REGION=us-west-2

      addons:
        apt:
          packages:
            - python
            - python-pip

      install:
        - pip install awscli --upgrade --user
        - npm ci

      script:
        - npm run doc-prepare
        - npm run doc-build

      deploy:
        provider: script
        script:
          - npm run doc-upload
        skip_cleanup: true
        on:
          all_branches: true

      after_deploy:
        - npm run doc-cloudfront
